name: Regression test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: |
        sudo apt-get install python3-virtualenv build-essential python-virtualenv
        sudo apt-get install libreadline-gplv2-dev libncursesw5-dev libssl-dev libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev
        sudo pip install hitchkey
    - name: Regression test
      run: |
        hk regression
